name: Checkout and Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          if [ -f "yarn.lock" ]; then
            yarn install
          else
            npm ci
          fi

      - name: Build project
        run: |
          if [ -f "yarn.lock" ]; then
            yarn build
          else
            npm run build
          fi

      - name: Verify Build
        run: echo "Build successful"
